language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - gcc-multilib

before_script:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install -f cargo-travis;
        export PATH=$HOME/.cargo/bin:$PATH;
      fi

after_success:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo coveralls --all;
      fi