[package]
name = "testrepo"
version = "0.1.0"
authors = ["Julian Blazek <mail@nailuj.net>","Nick Grüßner <n.gruessner@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"